name: extensionapp
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  fluttertoast: ^8.2.2
  device_preview: ^1.1.0
  url_launcher: ^6.2.1
  bip39: ^1.0.6
  wallet: ^0.0.12+1
  hex: ^0.2.0

  toast: ^0.3.0
  trust_wallet_core: ^0.0.6
  hd_wallet: ^0.0.9
  material_tag_editor: ^0.1.2
  logger: ^2.0.2+1
  ed25519_hd_key: ^2.2.1
  web3dart: ^2.5.1
  fl_chart:
  sqflite: ^2.3.0
  trust_wallet_core_lib: ^0.0.7+3.0.4
  tron: ^0.0.2
  fixnum: ^1.1.0
  loading_animation_widget: ^1.2.0+4
  qr_flutter:
#   ## Adiition Dapp setup

#   shared_preferences: ^2.2.2

#   animated_bottom_navigation_bar: ^1.3.0  
#   font_awesome_flutter: ^10.6.0


#   toggle_switch: ^2.1.0
#   flutter_staggered_animations: ^1.1.1
#   video_player: ^2.7.1
#   bip39: ^1.0.6
#   trust_wallet_core_lib: ^0.0.7+3.0.4
#   loading_animation_widget: ^1.2.0+4
  
#   material_tag_editor: ^0.1.2
#   http:
#   google_fonts:
#   intl:
#   dart_bs58check: ^3.0.2
#  # hex:
  walletconnect_flutter_v2: ^2.1.4
#   animated_item_picker: ^2.0.0
#   getwidget: ^4.0.0
#   webview_flutter_plus: ^0.3.0+2
#   sqflite: ^2.3.0
#   grpc: ^3.2.4
#   fl_chart:

#   smooth_page_indicator: ^1.1.0
#   cached_network_image: ^3.2.3
#   easy_localization: ^3.0.3
 

#   get_storage:
  
#   web3dart: 2.5.1
  
#   ed25519_hd_key: 2.2.0
  
#   bip32: ^2.0.0
#   # flutter_web3: 2.1.9
#   flutter_inappwebview: ^6.0.0-beta.24+1
#   dart_bip32_bip44: 0.2.0
 
  # tron: ^0.0.2
  
#   flutter_spinkit: ^5.2.0
  
#   marquee: ^2.2.3
  

#   #for tron Trasnstions
  quiver: ^3.2.1
  buffer: ^1.2.2
  #fixnum: ^1.1.0
  # protobuf_google: ^0.0.1
  protobuf:
  convert: ^3.1.1
  get_it: ^7.6.4
  eth_sig_util: ^0.0.9
  crypto: ^3.0.3
  http: ^1.1.0
  protobuf_google: ^0.0.1
  bs58: ^1.0.2
  
#   numeric_keyboard: ^1.1.0
#   local_auth: ^2.1.7
#   screenshot: ^2.1.0
#   image_picker: ^1.0.4

#   pointycastle: ^3.7.3
#   path_provider:
#   provider:
#   # wallet_connect_v2:
#   device_info_plus:
#   get_it_mixin:
#   share_plus:
#   share:
#   #wallet: ^0.0.12+1
#  # url_launcher: ^6.2.1
#   qr_code_scanner: ^1.0.1
#   qr_flutter:
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
